name: run notebook in micromamba environment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - run: ls

      - name: setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0'
          environment-file: climate-keeling.yml
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: 'all'
