name: run notebook in micromamba environment

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v4

      - name: setup micromamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: climate-keeling
          environment-file: climate-keeling.yml
          environment-name: climate-keeling
